import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  nl: {
    // Header & Navigation
    phone: '+31 6 16335723',
    email: 'mrelite.nl@gmail.com',
    about: 'Over Ons',
    services: 'Services',
    booking: 'Boeken',
    rates: 'Tarieven',
    language: 'Taal',

    // Hero
    tagline: 'INTERNATIONAL HIGH CLASS COMPANION SERVICE',
    welcome: 'Welkom bij Mr. Elite',
    heroDescription: 'Exclusieve begeleiding voor de meest veeleisende clientèle. Discretie, klasse en onvergetelijke ervaringen staan centraal in onze premium service.',
    contactNow: 'Contact Opnemen',

    // About
    aboutIntro: 'Over Mr. Elite',
    aboutIntro1: 'Mr. Elite biedt al meer dan 14 jaar exclusieve companion services aan een selecte internationale clientèle. Onze missie is het leveren van ongeëvenaarde kwaliteit en discretie.',
    aboutIntro2: 'Wij begrijpen dat onze klanten het allerbeste verwachten. Daarom werken wij uitsluitend met zorgvuldig geselecteerde professionals die voldoen aan onze strenge kwaliteitseisen.',
    aboutIntro3: 'Of het nu gaat om zakelijke evenementen, culturele gelegenheden of privé-arrangementen, Mr. Elite garandeert een service die uw verwachtingen overtreft.',
    aboutTitle: 'Waarom Kiezen Voor Mr. Elite',
    aboutText1: 'Onze jarenlange ervaring in de high-end companion industry heeft ons geleerd wat onze klanten werkelijk waarderen: betrouwbaarheid, professionaliteit en absolute discretie.',
    aboutText2: 'Elk van onze companions doorloopt een zorgvuldig selectieproces waarbij niet alleen uiterlijk, maar vooral intelligentie, sociale vaardigheden en culturele kennis centraal staan.',
    aboutText3: 'Van intieme diners tot internationale zakenreizen, wij zorgen ervoor dat elke ervaring perfect aansluit bij uw persoonlijke wensen en verwachtingen.',
    yearsExperience: 'Jaar Ervaring',
    satisfiedClients: 'Tevreden Klanten',
    availability: 'Beschikbaarheid',

    // Services
    servicesTitle: 'Onze Services',
    servicesSubtitle: 'Exclusieve services voor de meest veeleisende clientèle',
    arrangementsTitle: 'Arrangements',
    experiencesTitle: 'Experiences',
    arr1Title: 'Companionship Only',
    arr1Desc: 'Pure gezelschap en begeleiding voor sociale gelegenheden zonder verdere verplichtingen.',
    arr1F1: 'Sociale evenementen',
    arr1F2: 'Zakelijke bijeenkomsten',
    arr1F3: 'Culturele activiteiten',
    arr2Title: 'Dinner Date',
    arr2Desc: 'Elegante begeleiding tijdens een verfijnd diner in een exclusief restaurant.',
    arr2F1: 'Fine dining',
    arr2F2: 'Intieme gesprekken',
    arr2F3: 'Stijlvolle ambiance',
    arr3Title: 'Internationale Boeking',
    arr3Desc: 'Wereldwijde begeleiding voor zakenreizen en internationale evenementen.',
    arr3F1: 'Business travel',
    arr3F2: 'Internationale expertise',
    arr3F3: 'Meertalige begeleiding',
    arr4Title: 'Luxe Privé Rondvaart',
    arr4Desc: 'Exclusieve rondvaart met persoonlijke begeleiding',
    arr5Title: 'Paren- Swingersclub',
    arr5Desc: 'Begeleiding naar exclusieve clubs en feesten',
    arr6Title: 'Men for Men',
    arr6Desc: 'Speciale service voor mannelijke clientèle',
    exp1Title: 'BFE (Boyfriend Experience)',
    exp1Desc: 'Een authentieke en warme ervaring die voelt als een echte relatie.',
    exp1F1: 'Emotionele verbinding',
    exp1F2: 'Natuurlijke intimiteit',
    exp1F3: 'Persoonlijke aandacht',
    exp2Title: 'Fifty Shades of Perfect',
    exp2Desc: 'Een verfijnde en spannende ervaring voor de avontuurlijke klant.',
    exp2F1: 'Exclusieve setting',
    exp2F2: 'Bijzondere ervaring',
    exp2F3: 'Volledige discretie',
    exp3Title: 'Koppel Experience',
    exp3Desc: 'Speciale begeleiding voor koppels die samen een unieke ervaring willen.',
    exp3F1: 'Koppel begeleiding',
    exp3F2: 'Gezamenlijke activiteiten',
    exp3F3: 'Harmonieuze sfeer',
    exp4Title: 'Trio Experience',
    exp4Desc: 'Unieke ervaring met meerdere companions',
    exp5Title: 'Spa Experience',
    exp5Desc: 'Ontspanning en wellness begeleiding',
    exp6Title: 'First Time Experience',
    exp6Desc: 'Speciale begeleiding voor eerste keer',
    exp7Title: 'Double Couple Experience',
    exp7Desc: 'Begeleiding voor twee koppels',
    qual1Title: 'Betrouwbare en eerlijke service',
    qual1Desc: 'Transparante en professionele aanpak',
    qual2Title: 'Discreet bureau',
    qual2Desc: 'Uw privacy is gegarandeerd',
    qual3Title: 'Snelle en heldere communicatie',
    qual3Desc: 'Directe en duidelijke afspraken',
    bookNow: 'Nu Boeken',

    // Booking Form
    bookingTitle: 'Boekingsformulier',
    bookingSubtitle: 'Vul onderstaand formulier volledig in voor uw boeking',
    bookingHistory: 'Boekingshistorie',
    previousBookingLabel: 'Heeft u al eerder bij ons geboekt? *',
    previousBookingHint: 'Vul dan JA in om uw boekingsaanvraag te voltooien.',
    yes: 'Ja',
    no: 'Nee',
    clientTypeLabel: 'Ik ben een *',
    male: 'Man',
    female: 'Vrouw',
    couple: 'Koppel',
    personalInformation: 'Persoonlijke Gegevens',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    firstNamePlaceholder: 'Uw voornaam',
    lastNamePlaceholder: 'Uw achternaam',
    contactInformation: 'Contactgegevens',
    emailLabel: 'Emailadres *',
    confirmEmailLabel: 'Bevestig emailadres *',
    phoneNumber: 'Telefoonnummer *',
    emailPlaceholder: 'Emailadres',
    confirmEmailPlaceholder: 'Bevestig emailadres',
    phonePlaceholder: '+31 6 12345678',
    serviceSelection: 'Service Selectie',
    arrangementLabel: 'Ik wil een arrangement:',
    experienceLabel: 'Ik wil een experience:',
    companionLabel: 'Wie wilt u boeken? *',
    selectCompanion: 'Selecteer companion',
    extraServiceLabel: 'Extra dienst: (optioneel)',
    locationTiming: 'Locatie & Timing',
    countryLabel: 'Land van de boeking *',
    netherlands: 'Nederland',
    europe: 'Europa',
    outsideEurope: 'Buiten Europa',
    locationTypeLabel: 'Locatie van de boeking *',
    hotel: 'Hotel',
    privateVenue: 'Privé gelegenheid',
    dateLabel: 'Datum van de boeking *',
    dateNote: 'Datumnotatie: DD/MM/JJJJ',
    timeLabel: 'Starttijd boeking *',
    timeNote: '(Houdt alstublieft rekening met minimaal 1 uur reis- en voorbereidingstijd.)',
    selectTime: 'Selecteer tijd',
    durationLabel: 'Duur van de boeking (uren) *',
    selectDuration: 'Selecteer duur',
    paymentSection: 'Betaling',
    paymentLabel: 'Betaling van de boeking *',
    cashEuros: 'Contant in Euro\'s',
    bankTransfer: 'Bankoverschrijving',
    paymentRequest: 'Betaalverzoek bank',
    privacyAgreementText: 'Ik ga akkoord met de',
    privacyTerms: 'privacy voorwaarden',
    and: 'en',
    generalTerms: 'algemene voorwaarden',
    submitBooking: 'Boeking Versturen',
    submitting: 'Versturen...',
    preferDirectContact: 'Liever direct contact?',

    // Booking Confirmation
    bookingConfirmationTitle: 'Boeking Ontvangen',
    bookingConfirmationMessage: 'Hartelijk dank voor uw boeking! U heeft een bevestigingsmail ontvangen op uw emailadres. Wij nemen binnen 24 uur discreet contact met u op om de details te bespreken en uw afspraak te bevestigen.',
    newBooking: 'Nieuwe Boeking Maken',
    importantNotice: 'Belangrijke Mededeling',
    bookingNoticeText: 'Uw boeking wordt direct naar ons verzonden. Wij controleren uw aanvraag binnen 2 uur en nemen binnen 24 uur contact op voor bevestiging.',

    // Contact
    contactTitle: 'Contact',
    contactDescription: 'Voor meer informatie over onze services of om een afspraak te maken, neem discreet contact met ons op. Wij behandelen alle aanvragen met de grootste vertrouwelijkheid.',
    contactPhone: 'Telefoon',
    contactPhoneDesc: 'Bel voor directe service',
    contactEmail: 'E-mail',
    contactEmailDesc: 'Voor schriftelijke aanvragen',
    contactLocation: 'Locatie',
    contactLocationValue: 'Amsterdam, Nederland',
    contactLocationDesc: 'Internationale service beschikbaar',
    contactAvailability: 'Beschikbaarheid',
    contactAvailabilityValue: '24/7 Service',
    contactAvailabilityDesc: 'Altijd bereikbaar voor u',
    contactCtaTitle: 'Klaar voor een exclusieve ervaring?',
    contactCtaText: 'Neem vandaag nog contact met ons op voor een discrete consultatie. Wij bespreken graag uw wensen en zorgen voor een onvergetelijke ervaring.',
    sendEmail: 'E-mail Versturen',

    // Footer
    footerTagline: 'International high class companion service',
    privacyPolicy: 'Privacy Beleid',
    termsConditions: 'Algemene Voorwaarden',
    allRightsReserved: 'Alle rechten voorbehouden.',

    // Cookie Banner
    cookieText: 'Deze website gebruikt cookies om uw ervaring te verbeteren en onze service te optimaliseren. Wij respecteren uw privacy en gebruiken alleen essentiële cookies.',
    cookieAccept: 'Accepteren',
    cookieDecline: 'Weigeren',
    cookieLearn: 'Meer Informatie',

    // Tarieven
    tarievenTitle: 'Tarieven',
    tarievenSubtitle: 'Transparante prijzen voor onze premium services. Alle tarieven zijn inclusief BTW en gelden voor boekingen vooraf.',
    importantInfo: 'Belangrijke Informatie',
    tarievenInfoText: 'Deze tarieven gelden voor boekingen vooraf en als u binnen de eerste 30 minuten van uw boeking de boeking verlengt. Anders wordt het standaardtarief van € 250,- per uur gerekend.',
    tarievenDiscount: 'Speciale korting: Alle prijzen zijn 15% goedkoper dan de standaardtarieven!',
    hourlyRates: 'Uurtarieven',
    hoursCol: 'Uren',
    oneMan: '1 Man',
    coupleCol: 'Koppel',
    twoMen: '2 Mannen',
    hourUnit: 'uur',
    extraDay: 'Extra Dag',
    extraHour: 'Extra Uur',
    tarievenNote: '*Alle bovenstaande prijzen zijn in Euro\'s en inclusief BTW',
    tarievenFooter: 'Voor vragen over tarieven of speciale arrangementen, neem contact met ons op.',
    contactUs: 'Contact Opnemen',
    backToHome: 'Terug naar Home',

    // Gallery
    galleryTitle: 'Galerij',
    gallerySubtitle: 'Een impressie van onze wereld',

    // Testimonials
    testimonialsTitle: 'Klantrecensies',
    testimonialsSubtitle: 'Wat onze klanten over ons zeggen',
    testimonial1: 'Een absoluut fantastische ervaring. De discretie en professionaliteit waren ongeevenaard. Zeker een aanrader voor de veeleisende klant.',
    testimonial2: 'Mr. Elite heeft mijn zakenreis naar een hoger niveau getild. De begeleiding was perfect en de companion was buitengewoon intelligent en charmant.',
    testimonial3: ' discretie en kwaliteit van de service waren precies wat ik zocht. Ik zal zeker weer gebruik maken van hun services.',

    // Error Messages
    errorRequired: 'Dit veld is verplicht',
    errorFirstName: 'Voornaam is verplicht',
    errorLastName: 'Achternaam is verplicht',
    errorEmail: 'E-mail is verplicht',
    errorConfirmEmail: 'Bevestig e-mail is verplicht',
    errorPhone: 'Telefoonnummer is verplicht',
    errorCountry: 'Land is verplicht',
    errorLocationType: 'Locatie type is verplicht',
    errorDate: 'Datum is verplicht',
    errorTime: 'Tijd is verplicht',
    errorDuration: 'Duur is verplicht',
    errorPayment: 'Betaalmethode is verplicht',
    errorPrivacy: 'Privacy akkoord is verplicht',
    errorInvalidEmail: 'Ongeldig e-mailadres',
    errorEmailMatch: 'E-mailadressen komen niet overeen'
  },
  en: {
    // Header & Navigation
    phone: '+31 6 16335723',
    email: 'mrelite.nl@gmail.com',
    about: 'About',
    services: 'Services',
    booking: 'Booking',
    rates: 'Rates',
    language: 'Language',

    // Hero
    tagline: 'INTERNATIONAL HIGH CLASS COMPANION SERVICE',
    welcome: 'Welcome to Mr. Elite',
    heroDescription: 'Exclusive companionship for the most discerning clientele. Discretion, class, and unforgettable experiences are at the heart of our premium service.',
    contactNow: 'Contact Now',

    // About
    aboutIntro: 'About Mr. Elite',
    aboutIntro1: 'Mr. Elite has provided exclusive companion services to a select international clientele for over 14 years. Our mission is to deliver unparalleled quality and discretion.',
    aboutIntro2: 'We understand that our clients expect the very best. That is why we work exclusively with carefully selected professionals who meet our strict quality standards.',
    aboutIntro3: 'Whether it concerns business events, cultural occasions, or private arrangements, Mr. Elite guarantees a service that exceeds your expectations.',
    aboutTitle: 'Why Choose Mr. Elite',
    aboutText1: 'Our years of experience in the high-end companion industry have taught us what our clients truly value: reliability, professionalism, and absolute discretion.',
    aboutText2: 'Each of our companions undergoes a careful selection process where not only appearance, but especially intelligence, social skills, and cultural knowledge are central.',
    aboutText3: 'From intimate dinners to international business trips, we ensure that every experience perfectly matches your personal wishes and expectations.',
    yearsExperience: 'Years Experience',
    satisfiedClients: 'Satisfied Clients',
    availability: 'Availability',

    // Services
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Exclusive services for the most discerning clientele',
    arrangementsTitle: 'Arrangements',
    experiencesTitle: 'Experiences',
    arr1Title: 'Companionship Only',
    arr1Desc: 'Pure companionship and accompaniment for social occasions without further obligations.',
    arr1F1: 'Social events',
    arr1F2: 'Business gatherings',
    arr1F3: 'Cultural activities',
    arr2Title: 'Dinner Date',
    arr2Desc: 'Elegant accompaniment during a refined dinner at an exclusive restaurant.',
    arr2F1: 'Fine dining',
    arr2F2: 'Intimate conversations',
    arr2F3: 'Stylish ambiance',
    arr3Title: 'International Booking',
    arr3Desc: 'Worldwide accompaniment for business trips and international events.',
    arr3F1: 'Business travel',
    arr3F2: 'International expertise',
    arr3F3: 'Multilingual accompaniment',
    arr4Title: 'Luxury Private Cruise',
    arr4Desc: 'Exclusive cruise with personal accompaniment',
    arr5Title: 'Couples & Swingers Club',
    arr5Desc: 'Accompaniment to exclusive clubs and parties',
    arr6Title: 'Men for Men',
    arr6Desc: 'Special service for male clientele',
    exp1Title: 'BFE (Boyfriend Experience)',
    exp1Desc: 'An authentic and warm experience that feels like a real relationship.',
    exp1F1: 'Emotional connection',
    exp1F2: 'Natural intimacy',
    exp1F3: 'Personal attention',
    exp2Title: 'Fifty Shades of Perfect',
    exp2Desc: 'A refined and exciting experience for the adventurous client.',
    exp2F1: 'Exclusive setting',
    exp2F2: 'Special experience',
    exp2F3: 'Complete discretion',
    exp3Title: 'Couple Experience',
    exp3Desc: 'Special accompaniment for couples who want a unique experience together.',
    exp3F1: 'Couples accompaniment',
    exp3F2: 'Joint activities',
    exp3F3: 'Harmonious atmosphere',
    exp4Title: 'Trio Experience',
    exp4Desc: 'Unique experience with multiple companions',
    exp5Title: 'Spa Experience',
    exp5Desc: 'Relaxation and wellness accompaniment',
    exp6Title: 'First Time Experience',
    exp6Desc: 'Special accompaniment for first time',
    exp7Title: 'Double Couple Experience',
    exp7Desc: 'Accompaniment for two couples',
    qual1Title: 'Reliable and honest service',
    qual1Desc: 'Transparent and professional approach',
    qual2Title: 'Discreet agency',
    qual2Desc: 'Your privacy is guaranteed',
    qual3Title: 'Fast and clear communication',
    qual3Desc: 'Direct and clear agreements',
    bookNow: 'Book Now',

    // Booking Form
    bookingTitle: 'Booking Form',
    bookingSubtitle: 'Please fill out the form below completely for your booking',
    bookingHistory: 'Booking History',
    previousBookingLabel: 'Have you booked with us before? *',
    previousBookingHint: 'Fill in YES to complete your booking request.',
    yes: 'Yes',
    no: 'No',
    clientTypeLabel: 'I am a *',
    male: 'Male',
    female: 'Female',
    couple: 'Couple',
    personalInformation: 'Personal Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    firstNamePlaceholder: 'Your first name',
    lastNamePlaceholder: 'Your last name',
    contactInformation: 'Contact Information',
    emailLabel: 'Email address *',
    confirmEmailLabel: 'Confirm email address *',
    phoneNumber: 'Phone number *',
    emailPlaceholder: 'Email address',
    confirmEmailPlaceholder: 'Confirm email address',
    phonePlaceholder: '+31 6 12345678',
    serviceSelection: 'Service Selection',
    arrangementLabel: 'I would like an arrangement:',
    experienceLabel: 'I would like an experience:',
    companionLabel: 'Who would you like to book? *',
    selectCompanion: 'Select companion',
    extraServiceLabel: 'Extra service: (optional)',
    locationTiming: 'Location & Timing',
    countryLabel: 'Country of booking *',
    netherlands: 'Netherlands',
    europe: 'Europe',
    outsideEurope: 'Outside Europe',
    locationTypeLabel: 'Location of booking *',
    hotel: 'Hotel',
    privateVenue: 'Private venue',
    dateLabel: 'Date of booking *',
    dateNote: 'Date format: DD/MM/YYYY',
    timeLabel: 'Booking start time *',
    timeNote: '(Please allow at least 1 hour for travel and preparation time.)',
    selectTime: 'Select time',
    durationLabel: 'Booking duration (hours) *',
    selectDuration: 'Select duration',
    paymentSection: 'Payment',
    paymentLabel: 'Booking payment *',
    cashEuros: 'Cash in Euros',
    bankTransfer: 'Bank transfer',
    paymentRequest: 'Payment request bank',
    privacyAgreementText: 'I agree to the',
    privacyTerms: 'privacy terms',
    and: 'and',
    generalTerms: 'general terms',
    submitBooking: 'Submit Booking',
    submitting: 'Submitting...',
    preferDirectContact: 'Prefer direct contact?',

    // Booking Confirmation
    bookingConfirmationTitle: 'Booking Received',
    bookingConfirmationMessage: 'Thank you for your booking! A confirmation email has been sent to your email address. We will contact you discreetly within 24 hours to discuss the details and confirm your appointment.',
    newBooking: 'Make a New Booking',
    importantNotice: 'Important Notice',
    bookingNoticeText: 'Your booking will be sent directly to us. We will review your request within 2 hours and contact you within 24 hours for confirmation.',

    // Contact
    contactTitle: 'Contact',
    contactDescription: 'For more information about our services or to make an appointment, please contact us discretely. We handle all inquiries with the utmost confidentiality.',
    contactPhone: 'Phone',
    contactPhoneDesc: 'Call for direct service',
    contactEmail: 'Email',
    contactEmailDesc: 'For written requests',
    contactLocation: 'Location',
    contactLocationValue: 'Amsterdam, Netherlands',
    contactLocationDesc: 'International service available',
    contactAvailability: 'Availability',
    contactAvailabilityValue: '24/7 Service',
    contactAvailabilityDesc: 'Always reachable for you',
    contactCtaTitle: 'Ready for an exclusive experience?',
    contactCtaText: 'Contact us today for a discreet consultation. We are happy to discuss your wishes and provide an unforgettable experience.',
    sendEmail: 'Send Email',

    // Footer
    footerTagline: 'International high class companion service',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    allRightsReserved: 'All rights reserved.',

    // Cookie Banner
    cookieText: 'This website uses cookies to improve your experience and optimize our service. We respect your privacy and only use essential cookies.',
    cookieAccept: 'Accept',
    cookieDecline: 'Decline',
    cookieLearn: 'Learn More',

    // Tarieven
    tarievenTitle: 'Rates',
    tarievenSubtitle: 'Transparent prices for our premium services. All rates include VAT and apply to advance bookings.',
    importantInfo: 'Important Information',
    tarievenInfoText: 'These rates apply to advance bookings and when you extend your booking within the first 30 minutes. Otherwise the standard rate of € 250,- per hour applies.',
    tarievenDiscount: 'Special discount: All prices are 15% cheaper than the standard rates!',
    hourlyRates: 'Hourly Rates',
    hoursCol: 'Hours',
    oneMan: '1 Man',
    coupleCol: 'Couple',
    twoMen: '2 Men',
    hourUnit: 'hours',
    extraDay: 'Extra Day',
    extraHour: 'Extra Hour',
    tarievenNote: '*All prices above are in Euros and include VAT',
    tarievenFooter: 'For questions about rates or special arrangements, please contact us.',
    contactUs: 'Contact Us',
    backToHome: 'Back to Home',

    // Gallery
    galleryTitle: 'Gallery',
    gallerySubtitle: 'A glimpse into our world',

    // Testimonials
    testimonialsTitle: 'Client Reviews',
    testimonialsSubtitle: 'What our clients say about us',
    testimonial1: 'An absolutely fantastic experience. The discretion and professionalism were unmatched. Highly recommended for the discerning client.',
    testimonial2: 'Mr. Elite took my business trip to the next level. The accompaniment was perfect and the companion was exceptionally intelligent and charming.',
    testimonial3: 'The discretion and quality of service were exactly what I was looking for. I will definitely use their services again.',

    // Error Messages
    errorRequired: 'This field is required',
    errorFirstName: 'First name is required',
    errorLastName: 'Last name is required',
    errorEmail: 'Email is required',
    errorConfirmEmail: 'Confirm email is required',
    errorPhone: 'Phone number is required',
    errorCountry: 'Country is required',
    errorLocationType: 'Location type is required',
    errorDate: 'Date is required',
    errorTime: 'Time is required',
    errorDuration: 'Duration is required',
    errorPayment: 'Payment method is required',
    errorPrivacy: 'Privacy agreement is required',
    errorInvalidEmail: 'Invalid email address',
    errorEmailMatch: 'Email addresses do not match'
  }
};

const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'nl';
  });

  const t = (key) => {
    return translations[language][key] || key;
  };

  const switchLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, t, switchLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageProvider;
